### DISCUSSION TITLE
How to use Netmiko's delay_factor or global_delay_factor with Nornir

### DISCUSSION THREAD

**Discussion by ktbyers** [nornir-automation/nornir#633] [Q&A] [answered]
How do you use Netmiko's delay_factor or global_delay_factor in Nornir.

**Comment by ktbyers** [comment, marked as answer]
First, always set fast_cli = False in the ConnectHandler. Inventory format for this is:

```yaml
# Shows setting both fast_cli = False and global_delay_factor
eos:
  platform: eos
  connection_options:
    netmiko:
      platform: arista_eos
      extras:
        fast_cli: False
        global_delay_factor: 2
```

Then you would just add the delay_factor argument to your relevant call. For example,

```python
nr.run(task=netmiko_send_command, command_string="show ip int brief", delay_factor=4)
```

**Reply by bgile** [reply]
I set this up and my send_command is still trying to complete way too fast..
```
...
...
"connection_options":
  "netmiko":
    "extras":
      "conn_timeout": 240
      "fast_cli": False
      "global_delay_factor": 10
```
And the Send Command
```
arp = nr.run(task=netmiko_send_command,
                 command_string="show arp interface demux | no-more",
                 delay_factor=4)
```
Always fails waiting for a prompt because it's checking well before that command should be done running.  The command I am running takes a while as in some cases we are talking about thousands of entries I am trying to get.  Thoughts?  Did I miss something?  I've tried playing with the delay_factor and the result is always the same.

**Reply by bgile** [reply]
So I think I understand the issue..
On the readthedocs I read connection options as being at the same level as groups but it looks like there was 1 space indent?  hard to see haha:
```
   groups:
        - group_1
    connection_options:
        paramiko:
            port: 65020
            hostname:
            username: root
            password: docker
            platform: linux
            extras: {}
        dummy:
            hostname: dummy_from_host
            port:
            username:
            password:
            platform:
            extras:
                blah: from_host
```
But looking at your example, it seemed like connections_options was part of the groups so I adjusted it and it seems to work now.  I will continue to mess with devives that have larger ARP tables.

```
"groups":
  "Juniper":
    "username": {user}
    "password": {pw}
    "connection_options":
      "netmiko":
        "platform": "juniper_junos"
        "extras":
          "conn_timeout": 240
          "fast_cli": False
          "global_delay_factor": 4
```
