### DISCUSSION TITLE
Getting error trying to use napalm_get

### DISCUSSION THREAD

**Discussion by packe1bb** [nornir-automation/nornir#645] [Q&A] [answered]
I am new to Nornir, so apologies for the probably elementary question, however I am attempting to use Nornir to reach out to a collection of switches to run some tasks and am running into a lot of issues that I am slugging my way through one at a time.

I need to:
- Connect to a Cisco switch
- Determine what ports are access ports
- Push interface commands to all access ports on the switch/stack

I have been trying to find documented examples and figure it out by trial and error, but I am having a hard time finding documentation of this. It looks like napalm_get might be my best bet for collecting the interfaces and then using some logic, but using that raises 'napalm.base.exceptionsModuleImportError: Please provide a valid driver name.'

What am I missing? My lab switches are a mix of Cisco IOS, IOS-XE, and NX-OS switches. My code snippet provided below. Any insight would be greatly appreciated, thanks in advance!

```
from nornir import InitNornir
from nornir_napalm.plugins.tasks import napalm_get
from nornir_utils.plugins.functions import print_result

nr = InitNornir('config.yml')

interfaces = nr.run(napalm_get, getters=['get_interfaces'])
print_result(interfaces) 
```

**Comment by ktbyers** [comment, marked as answer]
What does your `config.yml` and inventory files look like? It sounds like you are not specifying the `platform` in inventory.

**Reply by packe1bb** [reply]
config.yml has the following:

```
inventory:
  plugin: SimpleInventory
  
  options:
    host_file: "<path>/hosts.yml"
    group_file: "<path>/groups.yml"
    defaults_file: "<path>/defaults.yml"

runner:
  plugin: threaded
  options:
    num_workers: 25

```
hosts.yml has entries for each switch in my lab following this:

```
<device name>:
  hostname: <IPv4 Address>
  groups:
    - <group name>
```

I did originally have the hosts.yml like below, but removed the platform to test because i was getting a module import error about cisco_ios being the platform and asking if the library was installed:

```
<device name>:
  hostname: <IPv4 Address>
  platform: cisco_ios
  groups:
    - <group name>
```

Is there a specific value that should be set for platform? I will be so happy if that is all I was doing wrong
