### DISCUSSION TITLE
could nornir_netmiko support telnet?

### DISCUSSION THREAD

**Discussion by MicShao** [nornir-automation/nornir#656] [Q&A] [answered]
when we use netmiko, it can support devices use telnet connect.(device_type: cisco_ios_telent)
How to do let nornir_netmiko can support devices only use telent connect?

**Comment by ktbyers** [comment, marked as answer]
Just set the platform to the proper device_type. I think something similar to the following should work:

```yaml
# Shows setting both fast_cli = False and global_delay_factor
ios:
  platform: cisco_ios_telnet
```

This is for a Nornir group named `ios`
