### DISCUSSION TITLE
Can't send ignore_warning statement to napalm

### DISCUSSION THREAD

**Discussion by max1on1** [nornir-automation/nornir#693] [Q&A]
Trying to send` ignore_warnings: True `to napalm driver with no success
```
connection_options:
  napalm:
    extras:
      optional_args:
        ignore_warning: True
```

**Comment by ktbyers** [comment]
@max1on1 Is this on a Junos device?

**Reply by max1on1** [reply]
Yes

**Reply by ktbyers** [reply]
Do you get an error or does it just not work? Have you tried this `ignore_warning=True` directly in NAPALM (i.e. outside of Nornir and verified that it works)?

**Reply by max1on1** [reply]
It just not work, but if i try `ignore_warning=True` directly in NAPALM, it work fine. Should this variable be passed to the driver from nornir config file?

**Reply by ktbyers** [reply]
It looks like to me that it should work i.e. the behavior should be identical between nornir_napalm and directly in napalm:

https://github.com/nornir-automation/nornir_napalm/blob/master/nornir_napalm/plugins/connections/__init__.py

Which versions of nornir and nornir_napalm are you using?

Also can you show me a very simplified base case of code where this failing? Also can you show me what failing looks like (i.e. how do you identify this as not working)?

**Reply by max1on1** [reply]
I try to send some 'delete' statetments to juniper e.g. 
```
delete_statetment = """
delete groups 
delete system
delete snmp
"""
```
and if 'snmp' section not in config i see error:

```
  File "/Users/maxon/venvs/nornir/lib/python3.6/site-packages/ncclient/operations/rpc.py", line 346, in _request
    raise RPCError(to_ele(self._reply._raw), errs=errors)
ncclient.operations.rpc.RPCError: warning: statement not found
```
if all section in config then work fine.

```
nr = InitNornir(config_file="./nornir_config.yaml")
send_config(nr)
```
```
config file:
logging:
  enabled: False

inventory:
  plugin: NetBoxInventory2
  options:
    nb_url: "***"
    nb_token: "***"
    ssl_verify: False
    filter_parameters: {"infrastructure_place": "***"}

connection_options:
  napalm:
    extras:
      optional_args:
        ignore_warning: True
```

**Reply by max1on1** [reply]
And now i will try this code:
```
    nr = InitNornir(config_file="./nornir_config.yaml")

    nr.inventory.defaults.connection_options["napalm"] = ConnectionOptions(
        extras={
            "optional_args": {
                "ignore_warning": True,
            },
        },
    )
```
and it work properly, problem only with yaml config

**Reply by ktbyers** [reply]
In your response above, which case fails (above you state they all work)?

**Reply by max1on1** [reply]
by config I meant config of junos

**Reply by ktbyers** [reply]
So this is what fails (if you have don't have any SNMP section in the Junos config)?

```
# nornir_config_yaml file
logging:
  enabled: False

inventory:
  plugin: NetBoxInventory2
  options:
    nb_url: "***"
    nb_token: "***"
    ssl_verify: False
    filter_parameters: {"infrastructure_place": "***"}

connection_options:
  napalm:
    optional_args:
      ignore_warning: True
```

And just to verify are there any connection_options > napalm coming from NetBox?
