### DISCUSSION TITLE
recursive connection_options with merged `extra` support

### DISCUSSION THREAD

**Discussion by viktorkertesz** [nornir-automation/nornir#761] [Ideas]
Dear Nornir community,
I'm curious about your opinion on the following matter:

# Problem
Currently `connection_options.extras` is a dict and the logic to access this attribute is that Host object `extras` is the top priority and then Group and Defaults follows. The `extras` attribute is simply overwritten in more specific configuration. However it would be nice to have this attribute as a merge of all the other `extras` defined in Host, Group and Defaults instances.

# Possible solution logic
\***First, I'd like to highlight that this behavior changes the API and must be communicated and use in upcoming main version!**\*

- Rewrite of `get_connection_options` logic in a way that defaults, group and host connection_options.extra parameters would be merged. Priority is defaults -> group1, group2,... -> host
So a host defined extra parameter would override defaults or groups if the key is the same. All distinct parameters will be merged together.
- Rewrite connection_options in Host class as property and alter access of this attribute to support recursion in runtime.
- Figure out how can we 'remove' certain parameter if we want to delete something instead of merge. Maybe a `None` value would do the trick.

# Benefits
We can better segment our `connection_options` extra parameters. We can define partial `extras` in defaults, groups and hosts.

# Downside of the new logic
If a user relies on that host defined extra will not merge but replace the default/groups, then the user might get additional parameters which might be unexpected.

# Example
defaults.yaml:
```
---
connection_options:
    netmiko:
        extras:
              secret: nornir
```
groups.yaml:
```
distant:
    connection_options:
        netmiko:
            extras:
                  timeout: 4
```
hosts.yaml:
```
host1:
    groups:
         - distant
    connection_options:
        netmiko:
            extras:
                  port: 222
```
# Old behavior
This will result in that host1 will NOT have the secret parameter nor the timeout value. Host file replace the extras.

# New behavior
host1 will have set the port 222, timeout of 4s and the secret set as well. Host file will merge the extras.

# TODO

- I added #759 but it is still very early and not complete.
- more comprehensive tests with more realistic inventory
- Complete docs on the behavior. (Currently there is no docs at all on this part of the inventory, not even for the original behavior)
