### DISCUSSION TITLE
Indented text not returned when using "netmiko_send_command"?

### DISCUSSION THREAD

**Discussion by zakhilton** [nornir-automation/nornir#850] [Q&A] [answered]
Hi Guys,

I am using nornir to manage manage some of my Avda FSP150  devices. When using a show command I am having an issue with returning all the output from the command, it appears that anything indented more than once seems to be ignored. For example if i run the below command i expect to get back the following output

### command 

show async-operation 26 async-job

### Output
```
async-job:
  progress-tracking-type:
    unit: percentage
    total: 100
    current: 100
    remaining: 0
  state: finished
  description: Executing backup current database

``` 

However when i use netmiko_send_command everything between "async-job" and "state" is missing from the returned output.

### Code

```python
Local_backup_result = task.run(netmiko_send_command, command_string=f"show async-operation {Proccess_ID} async-job")
print(Local_backup_result.result)
``` 

### Returned output

```
async-job: 
  state: in-progress
  description: Executing backup current database
``` 

Im fairly new to nornir / netmiko so any  suggestions on resolving this issue would be much appreciated.

Thanks,
