### DISCUSSION TITLE
Multiple inventories

### DISCUSSION THREAD

**Discussion by chatasos** [nornir-automation/nornir#899] [Q&A]
Hi,

A probably tricky question for a newbie: Is there a way to have multiple inventories being active at the same time?

I want to have a SimpleInventory with a yaml file and another custom inventory created on the fly (from various xls files).

I have tried adding the custom inventory entries to the initial inventory, using the following code:

```
for device in customdata:
  devicename = device['Name']
  deviceos = device['DeviceOS']

  nr.inventory.hosts[devicename] = Host(
    name = devicename,
    groups = [Group(deviceos), Group("scrapli")],
    hostname = devicename,
  )
```

Probably i'm missing something obvious, because the following code returns the correct platform (which is defined in groups.yaml) for the SimpleInventory entries, but None as the platform for the custom inventory entries. 

```
for device in nr.inventory.hosts:
  print(device)
  print(nr.inventory.hosts[device].platform)
```
At the same time i can see all (SimpleInventory + custominventory) Host records are there.

If i also update the platform attribute like below, then everything "seems" fine (besides scrapli connection_options as expected, which is not an issue for the devices in the custom inventory).

```

map_platform = {"IOS-XR": "iosxr", "IOS": "ios", "IOS-XE": "ios"}

for device in data:
  devicename = device['Name']
  deviceos = device['DeviceOS']

  nr.inventory.hosts[devicename] = Host(
    name = devicename,
    groups = [Group(deviceos), Group("scrapli")],
    hostname = devicename,
    platform = map_platform[deviceos]
  )

```

This is the groups.yaml file.

```
# groups.yaml
---
#used in hosts.yaml
iosxr:
  platform: 'iosxr'

#used in hosts.yaml
ios:
  platform: 'ios'

#used in custom inventory
IOS-XR:
  platform: 'iosxr'

#used in custom inventory
IOS:
  platform: 'ios'

#used in custom inventory
IOS-XE:
  platform: 'ios'

#used in hosts.yaml & custom inventory
scrapli:
  connection_options:
    scrapli:
      extras:
        auth_strict_key: False
```

I could guess a new plugin would be needed to support both input methods, but i was hoping to be able to cope around using the above workaround, unless i'm going to hit other issues.
