### DISCUSSION TITLE
Filtering by Groups works in a strange way.

### DISCUSSION THREAD

**Discussion by eudjinnl** [nornir-automation/nornir#997] [Q&A] [answered]
I've found a strange thing .
I use SimpleInventory plugin.
My test inventory:
defaults.yaml is empty

groups.yaml:
```
Cisco:
  connection_options:
    netmiko:
      extras:
        conn_timeout: 15
  platform: ios
Juniper:
  connection_options:
    netmiko:
      extras:
        conn_timeout: 15
  platform: junos
```

hosts.yaml
```
ciscotest:
  data:
    interfaces: {}
    ip: 192.168.1.1
    model: WS-C2960-48PST-L
    name: ciscotest
    os_version: 15.0(2)SE6
    role: Access Switch
    serial_number: sn1
    site: site__test1
    tenant: test1
    vendor: Cisco
  groups:
  - Cisco
  hostname: 192.168.1.1
juntest:
  data:
    interfaces: {}
    ip: 192.168.1.2
    model: WS-C2960-48PST-L
    name: juntest1
    os_version: 15.0(2)SE6
    role: Access Switch
    serial_number: sn2
    site: site__test1
    tenant: test1
    vendor: Juniper
  groups:
  - Juniper
  hostname: 192.168.1.2
```

Trying to filter with F function by group.

```
nornir_conf_file = Path('config_nornir_test_simple.yaml')
nornir_object = InitNornir(config_file=nornir_conf_file)
```

This works OK. I got the nornir_object Object with groups and hosts in inventory.

Then I filter it:
`device = nornir_object.filter(F(groups__contains = 'Cisco')) `
and get filtered host ciscotest inn device.invenroty. I've got what I wanted, but here is "__contains" and 'Cisco' is exact full name of theGroup. It looks strange.

If I try to filter with partial name of the group:
`device = nornir_object.filter(F(groups__contains = 'Cis')) `
device has NO filtered hosts in inventory

If I try to filter with exact name of the group and groups__eq:
`device = nornir_object.filter(F(groups__eq = 'Cisco')) `
device has NO filtered hosts in inventory

Is it me or it's a bug?
I've checked the latest version of nornir and v.3.3.0
Filtering with the exact name of a group is really inconvenient for me.
