### ISSUE TITLE
SimpleInventory: crash when a group does not have any value in groups.yaml

### ISSUE THREAD

**Issue by dmfigol** [nornir-automation/nornir#166]
`hosts.yaml`
```
isp1-pe1:
  nornir_host: 192.168.122.41
  nornir_username: admin
  nornir_password: admin
  nornir_nos: ios
  groups:
    - isp1
  type: network_device
isp2-pe1:
  nornir_host: 192.168.122.51
  nornir_username: admin
  nornir_password: admin
  groups:
    - isp2
  nornir_nos: ios
  type: network_device
```

`groups.yaml`
```
isp:

isp1:
  asn: 1000
  groups:
    - isp

isp2:
  asn: 2000
  groups:
    - isp
```

```
In [8]: nornir_runner = InitNornir(config_file="config.yaml")
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-8333d1930a09> in <module>()
----> 1 nornir_runner = InitNornir(config_file="config.yaml")

~/.pyenv/versions/3.7.0/lib/python3.7/site-packages/nornir/core/__init__.py in InitNornir(config_file, dry_run, **kwargs)
    264     inv_args = getattr(conf, inv_class.__name__, {})
    265     transform_function = conf.transform_function
--> 266     inv = inv_class(transform_function=transform_function, **inv_args)
    267 
    268     return Nornir(inventory=inv, dry_run=dry_run, config=conf)

~/.pyenv/versions/3.7.0/lib/python3.7/site-packages/nornir/plugins/inventory/simple.py in __init__(self, host_file, group_file, **kwargs)
    132 
    133         defaults = groups.pop("defaults", {})
--> 134         super().__init__(hosts, groups, defaults, **kwargs)

~/.pyenv/versions/3.7.0/lib/python3.7/site-packages/nornir/core/inventory.py in __init__(self, hosts, groups, defaults, transform_function, nornir)
    291 
    292         for group in self.groups.values():
--> 293             group.groups = self._resolve_groups(group.groups)
    294 
    295         self.hosts = {}

AttributeError: 'NoneType' object has no attribute 'groups'
```
Will submit PR.

**Comment by ktbyers** [comment]
This would work, but currently leaving it as empty or 'null' would fail.

```
isp: {}

isp1:
  asn: 1000
  groups:
    - isp

isp2:
  asn: 2000
  groups:
    - isp
```
