### ISSUE TITLE
Handling undefined groups

### ISSUE THREAD

**Issue by dmfigol** [nornir-automation/nornir#194]
I started thinking about this while working on #166 
There are situations when an undefined group is referenced. And this is a double-edged sword.
In some cases it is valid (from data consistency point of view). For example, a group does not have any vars:
```
isp:    # this group does not have any data, why define it?

isp1:
  asn: 1000
  groups:
    - isp

isp2:
  asn: 2000
  groups:
    - isp
```
Here is another situation, where there is a clear error:
```
isp: 

isp1:
  asn: 1000
  groups:
    - isp

isp2:
  asn: 2000
  groups:
    - ips   # this is a typo
```
The question is if we should silently create a group if it is not defined - this would be useful in the example 1, but it would probably hurt in an example 2.
If we shouldn't do that, I think we could still improve the code by adding more robust error message indicating which host/group didn't find another group.
