### ISSUE TITLE
Support for several connections using the same ConnectionPlugin

### ISSUE THREAD

**Issue by dmfigol** [nornir-automation/nornir#207]
For some of my problems I need to be able to connect to the same device using SSH and terminal server at the same time. Both of these connection types are supported by Netmiko, for example.
To be able to support this, there are a couple of things that needs to be implemented:
1) Support from inventory perspective. Potentially something like `serial_options`, but I need to investigate this more
2) Support from Host and Task classes, because currently the task using a specific plugin will use registered name like `napalm`, meaning that only one connection using that ConnectionPlugin can be opened for one host
For this part I am thinking about creating a way to specify a custom name to be stored in `host.connections` dictionary

I am still looking for a good API design, so feedback is welcome.
I will work on this once #195 is merged.

**Comment by ktbyers** [comment]
What if we implemented a second Netmiko connection type `netmiko_terminal_server` or `netmiko_serial`? I say this as then you could have one connection of each type for a given host.

You could also feed in different inventory arguments for the same host:

```
  netmiko_options:
    device_type: cisco_ios_telnet
    port: 23

netmiko_serial_options:
    device_type: terminal_server
    port: 22
```
