### ISSUE TITLE
Using 'transform_fuction' within 'config.yaml' doesn't work

### ISSUE THREAD

**Issue by bdlamprecht** [nornir-automation/nornir#219]
Currently, according to `@dbarrosop`, within the `config.yaml` file for a `nornir` inventory, you're able to define a `transform_function` such as this:
```yaml
---
num_workers: 100
inventory: nornir.plugins.inventory.netbox.NBInventory
NBInventory:
    nb_url: "http://netbox.local"
    nb_token: "[MY CUSTOM TOKEN]"
    transform_function: "my_lib.add_credentials"
```
The only caveat is that it "should be importable" and that you should be able to do this:
```
Python 3.6.5 (default, May  3 2018, 10:08:28)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import my_lib.add_credentials
>>>
```
However, this doesn't appear to work, as when I run this line of code:
```python
nr = InitNornir(config_file="config.yaml")
```
I get the following error:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bl839s/nornir/nornir/core/__init__.py", line 277, in InitNornir
    inv = inv_class(transform_function=transform_function, **inv_args)
TypeError: type object got multiple values for keyword argument 'transform_function'

```
I'm not sure why I'm doing incorrectly, but I'd appreciate any advice.

Also, along those same lines, `@dbarrosop` also asked that I open an issue to explore the idea of having it looks in `globals` so you could do the following (using the same `config.yaml`):
```python
>>> def add_credentials(host):
...     host.data["nornir_username"] = "[USERNAME]"
...     host.data["nornir_password"] = "[PASSWORD]"
...
>>> nr = InitNornir(config_file="config.yaml")
>>>
```

**Comment by ogenstad** [comment]
The indentation of your config file looks off, did you try moving `transform_function` up one level?

**Comment by dbarrosop** [comment]
Oh, I missed this issue. Yeah, what @ogenstad said :)

**Comment by dbarrosop** [comment]
Closing this one. Feel free to reopen if the problem persists after the change.

**Comment by bdlamprecht** [comment]
If I understand what you're asking correctly, I've tried moving the indentation of `transform_function` up one level and it didn't work:

```
num_workers: 100
inventory: nornir.plugins.inventory.netbox.NBInventory
NBInventory:
    nb_url: "http://netbox.local"
    nb_token: "[MY CUSTOM TOKEN]"
transform_function: my_lib.add_credentials
```

Not that this should matter, but I even moved the location of `transform_function` within the `yaml` file:
```
num_workers: 100
inventory: nornir.plugins.inventory.netbox.NBInventory
transform_function: my_lib.add_credentials
NBInventory:
    nb_url: "http://netbox.local"
    nb_token: "[MY CUSTOM TOKEN]"
```

These both produced the following traceback:
```
Traceback (most recent call last)
<ipython-input-2-91ab1091b65b> in <module>()
----> 1 nr = InitNornir(config_file="nornir.yaml")

~/nornir-bdlamprecht/nornir/core/__init__.py in InitNornir(config_file, dry_run, **kwargs)
    266     inv_args = getattr(conf, inv_class.__name__, {})
    267     transform_function = conf.transform_function
--> 268     inv = inv_class(transform_function=transform_function, **inv_args)
    269 
    270     return Nornir(inventory=inv, dry_run=dry_run, config=conf)

~/nornir-bdlamprecht/nornir/plugins/inventory/netbox.py in __init__(self, nb_url, nb_token, use_slugs, flatten_custom_fields, **kwargs)
     78 
     79         # Pass the data back to the parent class
---> 80         super().__init__(devices, None, **kwargs)

~/nornir-bdlamprecht/nornir/core/inventory.py in __init__(self, hosts, groups, defaults, transform_function, nornir)
    418 
    419             if transform_function:
--> 420                 transform_function(h)
    421 
    422             h.groups = self._resolve_groups(h.groups)

TypeError: 'module' object is not callable
```

If that is *NOT* what you were suggesting, please let me know and I'll try again.
