### ISSUE TITLE
Ansible inventory causes validation error

### ISSUE THREAD

**Issue by pehruby** [nornir-automation/nornir#267]
When I use an Ansible inventory file with Nornir 2.0.0b1, a validation error occurs when the inventory contains extra parameters.

Ansible inventory:
```yaml
---
  all:
    vars:
      ansible_python_interpreter: python
      ansible_connection: network_cli
      ansible_network_os: ios
      ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -p 10000 guest@10.105.152.50"'  # install ssh public key on proxy host !!!      
      env: staging
    children:
      virl:
        children:
          asa:
            vars:
              cisco_asa: True
              network_os: asa
              ansible_network_os: asa
              ansible_become: yes
              ansible_become_method: enable
              ansible_persistent_command_timeout: 30
            hosts:
              asa1:
                ansible_host: 10.255.0.2
                dot1x: True
          ios:
            vars:
              network_os: ios
              nornir_nos: ios
              platform: ios
            children:
              routers:
                hosts:
                  iosv-1:
                    ansible_host: 10.255.0.12
                  iosv-2:
                    ansible_host: 10.255.0.13
              access:
                hosts:
                  access1:
                    ansible_host: 10.255.0.6
              dist:
                hosts:
                  dist1:
                    ansible_host: 10.255.0.5
                  dist2:
                    ansible_host: 10.255.0.11
```
Part of the code:
```text
nr = InitNornir(core={"num_workers" :100},
                    inventory={
                        "plugin": "nornir.plugins.inventory.ansible.AnsibleInventory",
                        "options": {
                            "hostsfile": inventory_file
                            },
                        "transform_function": adapt_host_data
                    }
        )
```

Error message:
```text
Traceback (most recent call last):
  File "getdevpar.py", line 284, in <module>
    main()
  File "getdevpar.py", line 256, in main
    "hostsfile": inventory_file
  File "/home/ph/.local/lib/python3.6/site-packages/nornir/init_nornir.py", line 53, in InitNornir
    **conf.inventory.options,
  File "/home/ph/.local/lib/python3.6/site-packages/nornir/core/deserializer/inventory.py", line 111, in deserialize
    deserialized = cls(*args, **kwargs)
  File "/home/ph/.local/lib/python3.6/site-packages/nornir/plugins/inventory/ansible.py", line 251, in __init__
    hosts=host_vars, groups=group_vars, defaults=defaults, *args, **kwargs
  File "/home/ph/.local/lib/python3.6/site-packages/pydantic/main.py", line 166, in __init__
    self.__setstate__(self._process_values(data))
  File "/home/ph/.local/lib/python3.6/site-packages/pydantic/main.py", line 331, in _process_values
    return validate_model(self, input_data)
  File "/home/ph/.local/lib/python3.6/site-packages/pydantic/main.py", line 507, in validate_model
    raise ValidationError(errors)
pydantic.error_wrappers.ValidationError: 14 validation errors
hosts -> asa1 -> dot1x
  extra fields not permitted (type=value_error.extra)
groups -> asa -> ansible_become
  extra fields not permitted (type=value_error.extra)
groups -> asa -> ansible_become_method
  extra fields not permitted (type=value_error.extra)
groups -> asa -> ansible_network_os
  extra fields not permitted (type=value_error.extra)
groups -> asa -> ansible_persistent_command_timeout
  extra fields not permitted (type=value_error.extra)
groups -> asa -> cisco_asa
  extra fields not permitted (type=value_error.extra)
groups -> asa -> network_os
  extra fields not permitted (type=value_error.extra)
groups -> ios -> network_os
  extra fields not permitted (type=value_error.extra)
groups -> ios -> nornir_nos
  extra fields not permitted (type=value_error.extra)
defaults -> ansible_connection
  extra fields not permitted (type=value_error.extra)
defaults -> ansible_network_os
  extra fields not permitted (type=value_error.extra)
defaults -> ansible_python_interpreter
  extra fields not permitted (type=value_error.extra)
defaults -> ansible_ssh_common_args
  extra fields not permitted (type=value_error.extra)
defaults -> env
  extra fields not permitted (type=value_error.extra)
```
