### ISSUE TITLE
Merging of config file and InitNornir params (breaking change relative to v1)

### ISSUE THREAD

**Issue by optiz0r** [nornir-automation/nornir#291]
Hi

I had an issue in v1 where it is not possible to set some Inventory options in the config file, and set other options in the call to `InitNornir`. This is still present in v2 despite the rewrite because of the dict merge here: https://github.com/nornir-automation/nornir/blob/develop/nornir/core/deserializer/configuration.py#L170.

However in v1 it was possible to set options in the config file, and set a `transform_function` in the call to InitNornir because they were separate settings. In v2, transform_function has now been moved to a child of the inventory config, so trying to pass this into the InitNornir call means none of the inventory configuration from the config file is respected any more.

Having to define the `transform_function` in the config file, I think:
- blurs the lines between code and config data separation
- makes it much harder to reuse one config file across multiple nornir-based tools which might need different transforms, but otherwise reuse the inventory plugin options

IMHO `Config.load_from_file` does a partial merge between config data and parameters at too high a level (choosing to take one block at a time from either source). Especially now that the config file has been refactored to make the structures deeper, the merging should happen at least one level deeper than it currently is (it would also be useful if `inventory.options` dict were merged too, but that's not a change in behaviour from v1).

Example change which merges one level below the top, letting kwargs take precedence. This is perhaps not the nicest code (and does not handle merging of the inventory.options), but does restore what I think the previous behaviour was:
```python
    @classmethod
    def load_from_file(cls, config_file: str, **kwargs) -> configuration.Config:
        config_dict: Dict[str, Any] = {}
        if config_file:
            yml = ruamel.yaml.YAML(typ="safe")
            with open(config_file, "r") as f:
                config_dict = yml.load(f) or {}

        # Merge the config and parameters together
        merged_config = config_dict
        for k1 in kwargs:
            if k1 in merged_config:
                for k2 in kwargs[k1]:
                    merged_config[k1][k2] = kwargs[k1][k2]
            else:
                merged_config[k1] = kwargs[k1]

        return Config.deserialize(**merged_config)
```

What do you think?

**Comment by optiz0r** [comment]
if all variables were top-level variables the current merging behaviour would be fine. Because the config is deeply structured and the merging applies to the very top-most level only this is less useful than it could be, and forces a lot of complexity down to the end user code.

Imagine this more concrete example:
```yaml
# config.yaml
inventory:
  plugin: MyInventory
  options:
    # These are sane defaults, which we might want to override at runtime with cli option, or env var
    cache: true
    cache_file: "inventory/inventory.cache.yaml"
    base_url: "https://foo.local/api"
ssh:
  ssh_config: "some_config"
```
```python
class MyInventory(Inventory):
  def __init__(self, base_url, token, cache, cache_file, **kwargs):
    # Does stuff with params
    super().__init__(hosts={}, groups={}, defaults={}, **kwargs)

def my_transform(host, auth):
  # Does stuff with host.data and auth
  pass

def __main__():
  # probably argparse or similar
  args = parse_args_from_somewhere()
  # Assume in this case, script was run with --no-cache and args.cache=False

  # Includes the api secret
  auth = get_secrets_from_somewhere()

  inventory_config = {
    'options': {
      # This is secret, shouldn't be in a config file, or in code.
      # Maybe it relies on an env var, so is only obtainable at runtime
      'token': auth['token'],
    },
    # These should only be set at runtime because options are required:
    'transform_function': 'my_transform',
    'transform_function_options': {'auth_data': auth},
  )

  if args.cache is not None:
    inventory_config.update({'cache': args.cache})

  nr = InitNornir(inventory=inventory_config)
```

In this example, configuration data comes from three sources:
- code, e.g. transform functions
- config file, containing environment-specific static data, so wouldn't be committed to version control with code, but might be managed by some other CM system.
- runtime, e.g. debug, caching, noop/no-noop type options that might be set via environment vars or cli options

The resulting effective configuration should intuitively look like:
```yaml
inventory:
  plugin: MyInventory
  options:
    cache: false
    cache_file: "inventory/inventory.cache.yaml"
    base_url: "https://foo.local/api"
    token: "some secret token" # my initial sample code still doesn't handle this one, but I think this is still useful to have
  transform_function: '__main__.my_transform'
  transform_function_options: {some opaque data}
ssh:
  ssh_config: "some_config"
```

This doesn't work because by passing the `inventory` kwarg, masks the `inventory` defaults entirely like they were never set. So it actually looks like:
```yaml
inventory:
  # wrong plugin
  plugin: nornir.plugins.inventory.simple.SimpleInventory
  options:
    cache: false
    # missing cache_file
    # missing base_url
    token: "some secret token" # my initial sample code still doesn't handle this one, but I think this is still useful to have
  transform_function: '__main__.my_transform'
  transform_function_options: {some opaque data}
ssh:
  ssh_config: "some_config"
```

Nornir should indeed maintain a clear, documented order of precedence, I'm not arguing against this at all. I'm just trying to argue a case for the level at which precedence is applied being deeper into the object than the top-level.

The alternative is that if we need to set _any_ inventory options at runtime for _any_ reason, that we either:
- have to drop support for the inventory plugin configuration options (diverging from documentation)
- duplicate effort in having a separate config file (diverging from documentation)
- duplicate a whole lot of complex code to re-read the nornir config file a second time to extract those defaults in a different way than nornir core does. This way lies madness (having to fully understand the libraries used by nornir like pydantic) and tech-debt.

I think all three of these options are worse than increasing the config parser complexity to handle this properly in core?

With regards to the environment variable substitution, I'm having trouble re-creating the intended precedence behaviour. I can only get the env var to take effect if neither the config file nor the any `inventory` kwargs are passed. Where in the code are the overrides supposed to take effect?

**Comment by optiz0r** [comment]
Re env var overrides, I've just tried to add a test to capture the intended config<env override behaviour, and it fails, which matches my earlier manual testing:

```python
from nornir.plugins.inventory.nsot import NSOTInventory

    def test_configuration_file_override_env_inventory_plugin(self):
        os.environ["NORNIR_INVENTORY_PLUGIN"] = "nornir.plugins.inventory.nsot.NSOTInventory"
        config = ConfigDeserializer.load_from_file(
            os.path.join(dir_path, "config.yaml")
        )
        assert config.inventory.plugin == NSOTInventory
        os.environ.pop("NORNIR_INVENTORY_PLUGIN")
```

Which leads to:
```
==================================================== FAILURES ====================================================
___________________________ Test.test_configuration_file_override_env_inventory_plugin ___________________________

self = <tests.core.deserializer.test_configuration.Test object at 0x7f9c639a6518>

    def test_configuration_file_override_env_inventory_plugin(self):
        os.environ["NORNIR_INVENTORY_PLUGIN"] = "nornir.plugins.inventory.nsot.NSOTInventory"
        config = ConfigDeserializer.load_from_file(
            os.path.join(dir_path, "config.yaml")
        )
>       assert config.inventory.plugin == NSOTInventory
E       AssertionError: assert <class 'nornir.plugins.inventory.ansible.AnsibleInventory'> == NSOTInventory
E        +  where <class 'nornir.plugins.inventory.ansible.AnsibleInventory'> = <nornir.core.configuration.InventoryConfig object at 0x7f9c600ed870>.plugin
E        +    where <nornir.core.configuration.InventoryConfig object at 0x7f9c600ed870> = <nornir.core.configuration.Config object at 0x7f9c60155f10>.inventory

tests/core/deserializer/test_configuration.py:185: AssertionError
```

There are some existing tests which I think are intended to catch the override behaviour:
```python
    def test_configuration_file_override_env(self):
        os.environ["NORNIR_CORE_NUM_WORKERS"] = "30"
        os.environ["NORNIR_CORE_RAISE_ON_ERROR"] = "1"
        os.environ["NORNIR_SSH_CONFIG_FILE"] = "/user/ssh_config"
        config = ConfigDeserializer.deserialize()
        assert config.core.num_workers == 30
        assert config.core.raise_on_error
        assert config.ssh.config_file == "/user/ssh_config"
        os.environ.pop("NORNIR_CORE_NUM_WORKERS")
        os.environ.pop("NORNIR_CORE_RAISE_ON_ERROR")
        os.environ.pop("NORNIR_SSH_CONFIG_FILE")
```
which "passes", but because this method doesn't call `ConfigDeserializer.load_from_file()`, all it's doing is testing what happens when no config file is provided and the env var is set.

Taken together, these tests seems to confirm that the actual order of precedence is env<config<code. Also that env vars and configs are merged one level deeper than config files and code parameters are, so utterly inconsistent behaviour all round.

**Comment by optiz0r** [comment]
I've traced the env var issues back to what I believe is a fault in `pydantic>=0.15` (released late Nov 2018), and have submitted a PR to correct the behaviour upstream: https://github.com/samuelcolvin/pydantic/pull/341.

With env var overrides working again, I can see a workaround to this issue being for code to set/overwrite env vars before calling `InitNornir`. That way we get merging of the pydantic-named settings, and the expected precedence behaviour. config < env < code (merged via env overwrites) < code (exclusively replaced by parameters to `InitNornir`).

The downside to this is that in order to get `transform_function` and `transform_function_options` to be merged in, they would have to be serialised into env vars and deserialised again, which is both slow, and a security risk (when transform_function is used to fill sensitive data into the inventory, you don't want the content to leak out via env vars).

The more I think about this, the more I think that 'transform_function*` arguments should **not** be children of the inventory config at all. The Inventory plugin's job is to return data from multiple sources to nornir in a completely standardised format (even more so under v2 with the pydantic backed models, which don't allow for any change to the deserialiser class, it can only hold the hosts, groups and defaults objects and nothing else). The input to a `transform_function` will always have the same structure, and it shouldn't have to be written with a particular inventory plugin in mind. So why should it's configuration be tightly coupled into the inventory plugin's configuration?

A better config design might be:
```yaml
inventory:
  plugin: "blah.MyInventory"
  options: {base_url: "https://blah"}
transform:
  function: "blah.inventory_transform"
  options: {token: "blah"}
```

This way, `transform_function*` options can be passed in entirely from code, with no risk of affecting the `inventory` setup. I'm happy to work on a PR to separate this if you agree it's the right direction to head in.

**Comment by dbarrosop** [comment]
Good job with the env var issue, let's wait and see what they say.

> I think all three of these options are worse than increasing the config parser complexity to handle this properly in core?

I am more concerned about documenting behavior. I always say that if something is hard to explain it's probably a bad idea :P

To avoid doing things too complex, I basically see two options here:

1. We leave it as it is.
2. We do a deep merge for dicts and a replace for everything else. For instance:

```
---
blah:
    a: 1
    b: [2, 3]
    c:
       ca: 1
       cb: 2
       cc: [3, 4]
```

and 

```
---
blah:
    a: 11
    d: 4
    c:
       cc: [1, 2]
       cd: 7
```

would become:

```
---
blah:
    a: 11
    b: [2, 3]
    c:
       ca: 1
       cb: 2
       cc: [1, 2]
       cd: 7
    d: 4
```

This method will also work well with env variables as you can target specific things you want to override regardless of where they are. The thing that worries me a bit is that this is a breaking change but if it's helpful I am willing to do it without waiting for a major release.

> I think that transform_function* arguments should not be children of the inventory config at all.

I don't see it that way, the `transform_function` is part of the inventory process so I think the categorization is correct. In any case, I don't want to change that to avoid breaking things. As time progresses and we start evaluating another major release (not anytime soon) we can reevaluate things but for now we are stuck with it :P

@ktbyers @dmfigol do you have any thoughts about this?
