### ISSUE TITLE
Multiple tasks on one host at the same time in threads

### ISSUE THREAD

**Issue by dmfigol** [nornir-automation/nornir#325]
This issue was created to discuss the possibility of running multiple tasks at the same time on one host in threads.
There are two things that are needed to make this work:
* Implement an actual grouping mechanism. For example `nr.run` could accept a tuple of args instead of a single task
* Implement automatic connection handling for concurrent tasks. For example, if both of the tasks use `napalm` connection, the second task should open a new `napalm-2` connection and use that.

**Comment by dbarrosop** [comment]
>     * For example `nr.run` could accept a tuple of args instead of a single task

This is a bit more complex than this. You have to be able to pass different arguments to different tasks. Otherwise, you'd be running the same exact thing N times in parallel. So basically it requires a new entire method.

> `napalm` connection, the second task should open a new `napalm-2` connection and use that

Why is that necessary?

Overall I feel skeptical about this and my vote would be to keep it on hold until we have more use cases to see (a) if it's really needed and (b) what is it that people actually wants to do and why. In the meantime, a simple workaround for this is as simple as just "hacking" your inventory a little:

```
# groups.yaml
my_router00:
    #  this group is our actual device
   ...

# users.yaml
# We create one device per thread inheriting from my_router00
my_router00_thread00:
   groups: [my_router00]
my_router00_thread01:
   groups: [my_router00]
my_router00_thread02:
   groups: [my_router00]
my_router00_thread03:
   groups: [my_router00]
```
