### ISSUE TITLE
Hosts added to inventory using add_host() not inheriting group attributes

### ISSUE THREAD

**Issue by jrdwsn** [nornir-automation/nornir#419]
Hosts imported into the Inventory from CSV file (using the `add_host()` function) are not inheriting groups attributes.

Using the following function for basic import:

```python
def import_device_csv(norn, filename):
    """Imports devices from a CSV file into the Nornir inventory"""
    with open(filename) as f:
        reader = csv.DictReader(f)
        for row in reader:
            if row["protocol"] == "ssh":
                groups = ["cisco_ios"]
            elif row["protocol"] == "telnet":
                groups = ["cisco_ios_telnet"]
            norn.inventory.add_host(
                name=row["name"],
                hostname=row["ip_addr"],
                groups=groups
            )
```

As a test, I'm defining one host in the `hosts.yaml` file, and the other in `devices.csv` file:

```yaml
---
# hosts.yml file

device1:
    hostname: 1.2.3.4
    groups:
        - cisco_ios_telnet
```

```yaml
---
# groups.yaml file
cisco_ios:
    platform: ios

cisco_ios_telnet:
    platform: ios
    connection_options:
        netmiko:
            extras:
                device_type: cisco_ios_telnet
        napalm:
            extras:
                optional_args:
                    transport: telnet
```

The CSV for import:

```
name,ip_addr,protocol
device2,5.6.7.8,telnet
```

Initialising the inventory then importing hosts from the CSV:

```python
def main():

    nr = InitNornir(config_file="config.yaml")

    # Import CSV and populate inventory
    import_device_csv(nr, "devices.csv")

    import ipdb; ipdb.set_trace()
    ...
```

From the debugger, I can see the correct group is assigned but the inherited keys are not being picked up by CSV imported host `device2`:

```
ipdb> host1 = nr.inventory.hosts["device1"]
ipdb> host2 = nr.inventory.hosts["device2"]
ipdb> host1.groups
['cisco_ios_telnet']
ipdb> host2.groups
['cisco_ios_telnet']
ipdb> host1.platform
'ios'
ipdb> host2.platform
ipdb> 
```
