### ISSUE TITLE
Assigning host to group during runtime

### ISSUE THREAD

**Issue by Wyko** [nornir-automation/nornir#430]
### Question

Is there any way to programmatically add a host to a particular group in order to retrieve the attribute of that group through the host later?

### Use Case

I am trying to make an automated ASA upgrade application. In order to do so, I need to assign specific models a specific upgrade file. My `groups.yaml` looks like this:

```
ASA5515:
  data:
    required_version: 9.8(4)8
    asa_file: asa984-8-smp-k8.bin
    asdm_file: asdm-openjre-7122.bin
    rest_api_file: asa-restapi-132346-lfbff-k8.SPA
```
The group name is the model string returned by a fact getter. That way I can determine programmatically which upgrade file a target device will use rather than hardcoding model numbers for each device. After I get the ASA model number, I then need to assign it to the appropriate group in order to pull the appropriate image files.
