### ISSUE TITLE
Connection options extras are not merged when using inheritance

### ISSUE THREAD

**Issue by Alex131089** [nornir-automation/nornir#452]
Hello, 

it seems the connection options extras are not merged when using inheritance, for example: 

default.yml:
```yml
connection_options:
  netconf:
    extras:
      allow_agent: False
      hostkey_verify: False
```

groups.yml:
```yml
noverify:
  connection_options:
    netconf:
      extras:
        hostkey_verify: True
```

hosts.yml:
```yml
hostn:
  hostname: host
  platform: plt
  groups:
    - noverify
```

```py
print(nr.inventory.defaults.dict())
print(nr.inventory.hosts['hostn'].get_connection_parameters('netconf').dict())

{'hostname': None, 'port': None, 'username': '', 'password': '', 'platform': None, 'data': {}, 'connection_options': {'netconf': {'hostname': None, 'port': None, 'username': None, 'password': None, 'platform': None, 'extras': {'allow_agent': False, 'hostkey_verify': False}}}}

{'hostname': 'host', 'port': 22, 'username': '', 'password': '', 'platform': 'plt', 'extras': {'hostkey_verify': True}}
```

Expected:
```py
{'hostname': 'host', 'port': 22, 'username': '', 'password': '', 'platform': 'plt', 'extras': {'allow_agent': False, 'hostkey_verify': True}}
```

I guess that's related to: https://github.com/nornir-automation/nornir/blob/fde3631358919209fb587e95192409650a57fdfd/nornir/core/inventory.py#L248-L273

I'm not sure this is the behavior most people will expect?
