### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'encode' when no hostname specified

### ISSUE THREAD

**Issue by dragosstan2602** [nornir-automation/nornir#550]
Hi guys,
I was getting this exception thrown when not explicitly specifying the hostname value under the host in the inventory file.
```
---
vEOS-LSW01:
  groups:
    - tors

vEOS-LSW02:
  groups:
    - tors
```
I assumed it would default to the `host` value if the `hostname` value is not populated going by the docs (which have some hosts defined without `hostname` values).
