### ISSUE TITLE
Runner config.yaml is taking precedence over runner environment variables

### ISSUE THREAD

**Issue by ktbyers** [nornir-automation/nornir#726]
I was expecting the precedence to be (highest precedence to lowest precedence):

Inline Python > Environment Variable > Nornir Config File

I was using this simple test case (running Nornir 3.1.1):

```python
from nornir import InitNornir

nr = InitNornir(config_file="config.yaml")
print(f"Runner plugin: {nr.runner}")
print(f"num_workers: {nr.runner.num_workers}")
```

With the following config.yaml:

```yaml
$ cat config.yaml 
---
inventory:
  plugin: SimpleInventory
  options:
    host_file: inventory.yaml
runner:
  plugin: threaded
  options:
    num_workers: 7
```

With the following two environment variables set:

```
$ env | grep NOR
NORNIR_RUNNER_PLUGIN=serial
NORNIR_RUNNER_OPTIONS={"num_workers": 100}
```

Running that Python program shows:

```
$ python foo.py 
Runner plugin: <nornir.plugins.runners.ThreadedRunner object at 0x7f8fa1aad0d0>
num_workers: 7
```

So the config.yaml file was being preferred over the environment variables.

**Comment by ktbyers** [comment]
If I comment the following lines in my config.yaml file:

```yaml
---
inventory:
  plugin: SimpleInventory
  options:
    host_file: inventory.yaml
#runner:
#  plugin: threaded
#  options:
#    num_workers: 7
```

And switch my program to only print out nr.runner, I now get:

```python
from nornir import InitNornir


nr = InitNornir(config_file="config.yaml")
print(f"Runner plugin: {nr.runner}")
```

```
$ python foo.py 
Runner plugin: <nornir.plugins.runners.SerialRunner object at 0x7ff9fbd11a10>
```

Just to verify that my environment variable is properly set.
