### ISSUE TITLE
Set timeout if i use inventory plugin

### ISSUE THREAD

**Issue by Sivolen** [nornir-automation/nornir#772]
Hi!
 I use inventory plugin, but i don't understand how to set timeout for ssh connection. 
I have an error:

```
netmiko.ssh_exception.NetmikoTimeoutException: Paramiko: 'No existing session' error: try increasing 'conn_timeout' to 10 seconds or larger.

```
```

config.yaml

# groups file
inventory:
#  plugin: NBInventory2
  plugin: NetBoxInventory2
  options:
    defaults_file: "defaults.yaml"
    nb_url: 'https://10.0.2.18'
    nb_token: ' key'
    ssl_verify: False
    use_slugs: True
    flatten_custom_fields: True
    use_platform_napalm_driver: True
    filter_parameters:
        role: ["cs"]
```
```
defaults.yaml

connection_options:
  paramiko:
    extras:
      timeout: 10
  netmiko:
    extras:
     conn_timeout: 10
```
