### ISSUE TITLE
nxos_ssh: napalm_configure with replace=True calls nxos napalm plugin (instead of nxos_ssh)

### ISSUE THREAD

**Issue by vlisjak** [nornir-automation/nornir#991]
nornir groups:
```
nxos_ssh:
  password: admin
  platform: nxos_ssh
  username: admin
```

nornir hosts:
```
n9kv1:
  data:
    device_roles:
    - pe
    mgmt:
      ipv4_address: 10.255.0.6/24
      name: mgmt0
  groups:
  - nxos_ssh
  hostname: 10.255.0.6
```

This runs Ok:
`task.run(task=napalm_configure, configuration=task.host["config"], dry_run=dry_run, replace=False)
`

But this one fails with replace=True:
`task.run(task=napalm_configure, configuration=node_config, dry_run=dry_run, replace=True)
`

with below error ... I guess nxos.py should be called instaed of nxos.py?
```
../scripts/lab_reset.py --dry --node n9kv1
nxos_ssh
apply_configs*******************************************************************
* n9kv1 ** changed : False *****************************************************
vvvv apply_configs ** changed : False vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv ERROR
Subtask: napalm_configure (failed)

vvvv render_j2_template ** changed : False vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv INFO
% Configuration for node n9kv1 [role pe] generated from template ./templates/min_cfg/pe_nxos_ssh.j2.
^^^^ END render_j2_template ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
---- napalm_configure ** changed : False --------------------------------------- ERROR
Traceback (most recent call last):
  File "/home/vlisjak/scripts/myvenv310/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/vlisjak/scripts/myvenv310/lib/python3.10/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 37, in napalm_configure
    diff = device.compare_config()
  File "/home/vlisjak/scripts/myvenv310/lib/python3.10/site-packages/napalm/nxos/nxos.py", line 289, in compare_config
    diff = self._get_diff()
  File "/home/vlisjak/scripts/myvenv310/lib/python3.10/site-packages/napalm/nxos/nxos.py", line 271, in _get_diff
    diff_out.split("Generating Rollback Patch")[1]
IndexError: list index out of range

^^^^ END apply_configs ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
